jobs:
- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_stable'
    vmImage: 'macOS-latest'
    toolchain: 'stable'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_beta'
    vmImage: 'macOS-latest'
    toolchain: 'beta'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'macOS-latest'
    toolchain: 'nightly'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'Linux_stable'
    vmImage: 'ubuntu-latest'
    toolchain: 'stable'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'Linux_beta'
    vmImage: 'ubuntu-latest'
    toolchain: 'beta'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'Linux_nightly'
    vmImage: 'ubuntu-latest'
    toolchain: 'nightly'
